### ISSUE TITLE
Create RSS feed?

### ISSUE THREAD

**Issue by kimjoar** [superherojs/superherojs#20]
Many have asked for an RSS feed, should we create one?

**Comment by olav** [comment]
We could merge this with the newsletter, by creating a blog with Jekyll (or something else), use its feed as the RSS feed, and send new blog posts (feed entries) to the mailing list as well.

Of course, if the feed should have one entry for each new addition, we might need something else.

**Comment by kimjoar** [comment]
I think that's a good idea. Just update the RSS feed every time we send a newsletter, and maybe create a super simple blog-ish kinda thing.

**Comment by mobmad** [comment]
+1. Let's keep it simple. Since we're not adding new resources very often, it shouldn't be a problem to maintain a feed manually?

Suggestion:
Batch up changes and publish them at most once pr. week. Publish all changes at once. Crosspost to twitter, manually update and create newsletter and RSS feed.

**Comment by kimjoar** [comment]
Newsletter one to two times a month at most, and manually maintaining the feed and newsletter seems like a good choice. I think we can update Twitter every time a new resource is added, where we also mention the creator of the resource, e.g. "We just added a great resource on JavaScript testing by @somenamehere. Come learn more about ...". Retweetable + it's a great way to let the creator know about it :)

I think we should also use Twitter for input, such as asking for great resources on a topic for example.

**Comment by mobmad** [comment]
RSS feed implemented
