### ISSUE TITLE
JavaScript Garden

### ISSUE THREAD

**Issue by mobmad** [superherojs/superherojs#25]
http://bonsaiden.github.io/JavaScript-Garden/

**Comment by kimjoar** [comment]
No longer relevant in the same way as before (ES2015 et al). Closing.

**Comment by mikaelbr** [comment]
@kjbekkelund Are you sure? The new syntactic sugar doesn't change any of the underlying semantics or the inner workings of both context or prototypes. I might be considered conservative in the later JS years, but I think it is very important to know how prototypes work and how context work. There might be better resources for it, but I think it just as - if not even more - important as before. (I believe firmly that good JS developers need to know that there is no such thing as class, but it is syntactic sugar for prototypes. Not class as you might expect from other languages.)

**Comment by kimjoar** [comment]
@mikaelbr Good points. Never really got through the content (as I think it's difficult to read, but might just be the typography and design that's throwing me off). I'm open to adding it if you're a fan of the content. :+1:

**Comment by mikaelbr** [comment]
I don't think this is necessarily the best resource. I agree with the ease of read. But I don't think the content it self is out dated, and I think we definitely need to cover it.

**Comment by kimjoar** [comment]
Agreed. I would prefer something that also cover some of the ES2015 stuff, where it's relevant.

**Comment by mikaelbr** [comment]
I'll add it as a request, tho we have articles on both inheritance and `this`/context. Might look for more modern iterations though. But luckily, they haven't been "deprecated"/outdated yet.
