### ISSUE TITLE
FRP

### ISSUE THREAD

**Issue by hequ** [superherojs/superherojs#36]
What about adding info about frp (functional reactive programming)? Very usefull concept especially when considering front-end development, but I've seen this used with node as well.

https://github.com/baconjs/bacon.js

**Comment by kimjoar** [comment]
I'm still looking for the best resources that explain FRP. We don't want to add links directly to libraries. Any suggestions?

**Comment by mikaelbr** [comment]
I really think this is the best article on the subject (at the very least in the JS domain): _The introduction to Reactive Programming you've been missing_ - https://gist.github.com/staltz/868e7e9bc2a7b8c1f754

An continuously updated post with many good illustrations and a lot of comments discussing the topic. It's pretty much the article I wish I'd written about the topic.

**Comment by kimjoar** [comment]
Awesome article, @mikaelbr. Prepping for a new "release", so waiting for a couple more changes before deploying this
