### ISSUE TITLE
More link suggestions

### ISSUE THREAD

**Issue by poweribo** [superherojs/superherojs#38]
taken from my reading list while reviewing my JS

http://elegantcode.com/2011/03/24/basic-javascript-part-12-function-hoisting/  (series)
http://blog.adtile.me/2014/01/16/a-dive-into-plain-javascript/
http://bonsaiden.github.io/JavaScript-Garden/
http://www.digital-web.com/articles/seven_javascript_techniques/
http://www.bolinfest.com/javascript/inheritance.php
http://javascriptenlightenment.com/
https://developer.mozilla.org/en/A_re-introduction_to_JavaScript
http://peter.michaux.ca/ (wealth of js articles)
http://www.klauskomenda.com/code/javascript-programming-patterns/

http://bevacqua.io/buildfirst
http://www.addyosmani.com/resources/essentialjsdesignpatterns/book/

**Comment by kimjoar** [comment]
@poweribo Thanks for the links. Sorry for the laaate response. We've had a bit of a break, but now we've ready to start working more with the site again.

We already have resources that cover some of these topics. The one that interest me the most is http://blog.adtile.me/2014/01/16/a-dive-into-plain-javascript/. It would be interesting to have a good resource on using working with the DOM instead of using jQuery et al. @mikaelbr @mollerse @mobmad  Thoughts?

**Comment by mikaelbr** [comment]
I liked some parts of the article. Namely the focus of progressive enhancement, feature detection and that it is a very light and easy read. 

But there are also some concerns. I didn't like the article suggesting to extend the prototype (adding `.on` method), and the entire middlepart is more of a "replace your jquery with vanilla js"-article, not necessarily "understand vanilla js". The end has some weirdly specific examples of image resizing.

I think we should have another light resource for doing "modern vanilla JS" in the "Understanding JavaScript" section, but I'm not too sure this is it. It might be, as it shows the most basic examples, and if you are familiar with jQuery this can show you how the vanilla counterpart is. But I think we also can look some around, to see if there are any alternatives.

**Comment by kimjoar** [comment]
@mikaelbr Maybe we could add a "Request for resources: modern vanilla JS" issue? (Or maybe "Request for resources" can be a label, which we can link to from our contribution file?)

**Comment by mikaelbr** [comment]
Good idea. I'll create a "request" label, and link to it from the contribution document.

**Comment by kimjoar** [comment]
Let's continue the discussion in https://github.com/superherojs/superherojs/issues/53
