### ISSUE TITLE
Missing favicon

### ISSUE THREAD

**Issue by jcubic** [superherojs/superherojs#44]
There is no favicon on the site.

**Comment by kimjoar** [comment]
@olav Any ideas for a favicon?

**Comment by mikaelbr** [comment]
Not much of a graphical genius or creative favicon-maker, but it seems that the most obvious solution can work: The superman logo. 

The advantage is that it is pretty simplistic in shape and is fairly recognizable as a superhero-emblem.

I fired up my mad skills at http://pixlr.com and sketched something:

![superherojs](https://cloud.githubusercontent.com/assets/606374/4967753/f12b770a-6822-11e4-9f54-be7d538ed534.png)

The main idea is Superhero.js red as border, and JS yellow as background with the JS font.

Available as favicon here, to see if it works in a small size: [demo](https://dl.dropboxusercontent.com/u/2361994/superherojs/index.html) - [source](https://dl.dropboxusercontent.com/u/2361994/superherojs/favicon.ico)

![screen shot 2014-11-09 at 17 18 50](https://cloud.githubusercontent.com/assets/606374/4967967/266e475e-682c-11e4-93d3-0b17c3235bbd.png)

**Comment by olav** [comment]
@mikaelbr Awesome stuff, that icon is definitely recognisable. :) I'll publish.
