### ISSUE TITLE
Linking to new resources on Twitter

### ISSUE THREAD

**Issue by kimjoar** [superherojs/superherojs#50]
Thinking about how we should inform about new resources. What about something like this:

> New resource added: @someuser's "The title of the blogpost/video/book", https://link-to-resource

Should the link be to superherojs.com or to the actual resources? I prefer the latter, as it shouldn't be necessary to go to our page to find the link you're interested in. However, linking to our site means people might easily find other things they're interested in...

@mikaelbr @olav @mollerse @mobmad Thoughts? Does the tweet content look ok?

**Comment by mikaelbr** [comment]
I'm thinking it is pretty annoying for a link resource to route the traffic through their own site. You are pressing the link to read the link, IMO. And if they are interested in looking at superherojs.com they can easily find it through the Twitter handle, or?

The tweet scheme looks fine by me. I'm thinking also the Twitter account can be used for other articles as well? Articles that are good and worth a read to understand JS, but not necessarily the kind of article we are interested in having at the site?

**Comment by kimjoar** [comment]
Agreed, @mikaelbr. Let's not be annoying. It's a better experience coming directly to the resource.

I think we should use the Twitter account to spread a wider range of articles than the ones we feature on the site. One way of doing this can also be to more actively retweet.

Perhaps we can also use the Twitter account to ask for resources on a topic we're interested in?

**Comment by mikaelbr** [comment]
My theory is that Twitter accounts should be a "living" entity to keep it alive and accumulate followers. But  I feel original tweets with "manual" recommendations gives a better impression of quality control? But of course RT tweets if that is more natural (to give correct attributions).

The Twitter account should definitely be a two-way communication unit, where we can ask for resources.

**Comment by mollerse** [comment]
:+1: for not being annoying with the links. People will discover the site through the Twitter profile or Google just fine.

I like curation efforts that actually add something more rather than just parrot. For example, adding a "Why is this a good resource" or "why should you read this article" to a link. It does require more time and effort though.

**Comment by kimjoar** [comment]
Awesome. I agree, let's try to add to to the conversations, not just retweet (Unless, of course, the tweet itself is the thing we want to share).

**Comment by olav** [comment]
Sounds good! The "new resource tweet template" could also include the person who added the resource, if it's not one of us. Something like:

> New: @someuser's "The title of the blogpost/video/book", https://link-to-resource. Thanks @someotheruser.

**Comment by kimjoar** [comment]
Great idea, @olav. Let's try to keep that in mind :)
