### ISSUE TITLE
We need a CONTRUBITING.md

### ISSUE THREAD

**Issue by kimjoar** [superherojs/superherojs#51]
This is great stuff: https://github.com/bolshchikov/js-must-watch/blob/master/contributing.md

We need to add our own!

Some things we should include:
- Only add/delete/change 1 resource per pull request
- Make sure the resource haven't been discussed already
- Make sure to specify why it is an awesome resource: what did you learn and what others can learn from it
- We prefer resources that don't overlap much with our existing resources (If they do overlap, make sure to specify why this is a better resource)
- We prefer resources that don't focus on specific tools

By the way, these are some of the topics we are interested in resources about:
- Building JavaScript apps. We don't want resources that focus on Grunt, Gulp or Makefiles, but focus on those things that matter whatever tool you choose.
- JavaScript architecture. How to build large-scale JavaScript apps.
- Virtual DOM

@mollerse @mikaelbr Any of you want to take a stab at an initial pull request for this?

**Comment by mikaelbr** [comment]
You've pretty much covered most of it here, and they are great points! I'll give it a go, writing an initial PR with a document.

**Comment by mikaelbr** [comment]
Opened PR #52

**Comment by mollerse** [comment]
Do we also want some other sorts of contributions other than PRs? For example, are we interested in discussions in PRs or issues? Or requests for resources? Something along the lines of "I want to learn about X, do you know any good resources?".

If so, we should add something to outline how discussions can be held in an open and  friendly manner. Could have a look at [npm CoC](http://www.npmjs.com/policies/conduct/) and [Rust CoC](https://github.com/rust-lang/rust/wiki/Note-development-policy#conduct) for some input on this.

**Comment by kimjoar** [comment]
I'll close this in favor of #52.
