### ISSUE TITLE
Modern Vanilla Javascript

### ISSUE THREAD

**Issue by mikaelbr** [superherojs/superherojs#53]
We need a resource for covering modern style, proper language, "vanilla" javascript for the Browser. This should be a resource that covers how to write modern applications with DOM manipulation and event handling without any abstractions like jQuery.

One suggested possibility from issue #38 is [A Dive Into Plain JavaScript](http://blog.adtile.me/2014/01/16/a-dive-into-plain-javascript/).

**Comment by kimjoar** [comment]
Anyone read http://www.domenlightenment.com/? Might be an interesting in-depth resource to check out. Perhaps it could be coupled with a far more lightweight introductory blog post or video? (I guess we should beware of only adding books and other huge resources)

**Comment by Kedarnath-Rothe** [comment]
Please assign this issue to me
