### ISSUE TITLE
Virtual DOM and Component Based Architecture

### ISSUE THREAD

**Issue by mikaelbr** [superherojs/superherojs#55]
We need good resources describing the general concept of Virtual DOMs and how this "new wave" of view-layer components is used and how it works.

**Comment by kimjoar** [comment]
What about something like http://jbi.sh/what-is-virtual-dom/?

**Comment by mikaelbr** [comment]
I like it. It isn't that extensive it self, and acts like more of a summary/explanation of what it is, and it is quite easy to just read the post and get a feel for the Virtual DOM. But whats more interesting, the post has collection _many_ links for more advanced posts and different implementation specific examples (from Elm to React to virtual-dom). It actually links to most of the resources I've seen on the topic.
