### ISSUE TITLE
Human JavaScript

### ISSUE THREAD

**Issue by mollerse** [superherojs/superherojs#58]
Prompted by: https://twitter.com/HenrikJoreteg/status/535152676338540544

Off the top of my head, its been a while since i read the book:

**Pros**
- Freely available
- Is up to date and kept up to date
- Features a complete application
- Very understandable language
- Short and to the point

**Cons**
- Biased towards a single _Right Way_(tm)
- Has alot of liberary-specific stuff
- Heavily based around applications, not just web development in general (this might not be an issue, but including it for completeness)

The one thing already in our collection which it seems natural to compare it to is JavaScript Web Applications by Alex MacCaw. I've read both, but as it has been a while i think I want to quickly flip through them again for a more complete verdict.

Thoughts? @mikaelbr @kjbekkelund

**Comment by kimjoar** [comment]
To me there is maybe a little too much library-specific stuff. But that is of course also a problem with our existing resource (JavaScript Web Applications, which focuses on Spine)

How is reading this book if you don't have any experience with Backbone? Still understandable?

I think a heavy focus on apps is great. We need more resources with this focus.

**Comment by Kedarnath-Rothe** [comment]
Please assign this issue to me
