### ISSUE TITLE
Tweet: http://jsforcats.com/

### ISSUE THREAD

**Issue by mikaelbr** [superherojs/superherojs#60]
Maybe not as thorough and extensive as some of our existing introductions, but a easy-to-read, very much beginner level, resource that'd be worth tweeting.

Maybe our followers isn't really the target for beginner-level content? But it's nice to keep the twitter profile alive.

**Comment by kimjoar** [comment]
Agreed, it's worthy a tweet! +1 from me

**Comment by mikaelbr** [comment]
Tweeted this now. Superhero.js is alive.
