### ISSUE TITLE
'You Don't Know JS'

### ISSUE THREAD

**Issue by kurtinatlanta** [superherojs/superherojs#75]
Surprised these books aren't in your list.

https://github.com/getify/You-Dont-Know-JS

**Comment by mikaelbr** [comment]
You are completely right. Something that definitely should be on the list 👍 Feel free to submit a PR and I'll merge it as soon as I can.

**Comment by mikaelbr** [comment]
Added in 628dbd904d905aabaee387beb844bdcd4098125d.
