### ISSUE TITLE
Great work! (some suggestions)

### ISSUE THREAD

**Issue by benjamingr** [superherojs/superherojs#8]
First of all, great work! A really nice and comprehensive list of good resources all in one place. Defiantly a place to direct newbies to.

I think you should add JavaScript garden, it's also a really nice resource I think you're missing.

Addy Osmani's JavaScript design patterns is also a free and awesome book

**Comment by olav** [comment]
Thank you so much, we really appreciate your comments.

JavaScript garden and Addy Osmani's books seem like great resources, we'll check them out.
