### ISSUE TITLE
dotenv-linter addition

### ISSUE THREAD

**Issue by RickNln** [superherojs/superherojs#81]
We’ve recently announced a new open-source project - dotenv-linter, a lightning-fast tool to check your .env files for problems. dotenv-linter is written in Rust and can be used on any project regardless of the programming language.

Here the article where we share the details of the project: https://evrone.com/dotenv-linter

Github link: https://github.com/dotenv-linter/dotenv-linter

I'm sure it would be a good addition to your resource!

**Comment by mikaelbr** [comment]
Hi, thanks for your suggestion. Superherojs Is more about fundemental knowledge and «timeless» articles, and I don’t think this applies to that. Good luck with your project, though!
